#!/bin/bash

#ddev-generated

## Description: Run lighthouse and prepare reports
## Usage: lighthouse 
## Example: "ddev lighthouse"
## ExecRaw: true
# export NODE_TLS_REJECT_UNAUTHORIZED='0'
lhci autorun --collect.outputDir=~/export || true
tar -cf - *.json *.html | tar -xvf - -C export/
ls -l export/