#!/bin/bash

#ddev-generated

## Description: Run lighthouse and prepare reports
## Usage: lighthouse 
## Example: "ddev lighthouse"
## ExecRaw: true
# export NODE_TLS_REJECT_UNAUTHORIZED='0'

CONFIG_FILE=${1:-'lighthouserc.js'}

if [ ! -f ./config/$CONFIG_FILE ]; then
  echo "Config file ./config/$CONFIG_FILE not found"
  exit 1
fi

lhci autorun --config=./config/$CONFIG_FILE --collect.outputDir=~/export
ls -l ~/export/